### PR TITLE
FGK-101 Tamper function added

### PR DESCRIPTION
**Pull request by priknr1**
FGK-101 Tamper function added

### CODE REVIEW

**Comment by RobinBol** [comment]
I have the feeling you missed my previous message, hence: bump!

**Comment by priknr1** [comment]
I did miss it, sorry, I will have a look at it asap.   Hope I figure out what you mean.  (it's the copy/paste developer here :S :P )

**Comment by jeroenvollenbrock** [comment]
Hi, Thank you for contributing to this app. Unfortunately, there are a few things that need to be resolved before this PR can be merged. Could you please resolve the merge conflicts, apply the change that @RobinBol requested and sign the [CLA](https://cla-assistant.io/athombv/com.fibaro?pullRequest=131)?

**Comment by RobinBol** [comment]
Closing this PR due to inactivity, re-applied the changes here: https://github.com/athombv/com.fibaro/tree/FGK-101_tamper_capability_support.

**Pull request closed without merging**
