### PR TITLE
FGSS-001: Add device specific settings

### PR DESCRIPTION
**Pull request by Inversion-NL**

### CODE REVIEW

**Comment by WeeJeWel** [comment]
Thanks! Note that the 'parser' function for settings is optional when using numbers or booleans as setting types.

**Comment by Inversion-NL** [comment]
So how should I do it?
And what's the advantage of the parser function?

**Comment by Inversion-NL** [comment]
@RobinBolscher Can you answer this question, please?

**Comment by RobinBol** [comment]
Basically that this:

```
"parser": function( input ) {
				return new Buffer([ parseInt(input) ]);
			}
```

Is superfluous when the setting it is used for is of type number or boolean. The z-wave driver code will automatically parse the value into a buffer of the correct size (as specified).

**Pull request merged**
