### PR TITLE
update FGK-101 to use internal BASIC_SET report

### PR DESCRIPTION
**Pull request by caseda**

### CODE REVIEW

**Comment by caseda** [comment]
well, why wouldn't it work, if it triggers the 1st report parser, they are both different CC's
or do you think it will cause interference (the sensor really only triggers basic_set with the hardware changes)
but no, i didn't test it for this module.
i can ask someone if he wants to test it, if you really want it tested.

It did work for an aeotec module (don't know which one from the top of my head), and it didn't make the MS6 stop working, so i guess it would work for the fibaro fgk-101 as well.

**Comment by RobinBol** [comment]
Okay, but there is definitely a difference between not breaking things, and working. So yes, I'd like the changes to be tested. But this we can do ourselves as well of course. But for future PRs it would be advisable to only commit changes on devices that you can test, or notify me that the changes are not tested, then I'll do that myself.

**Comment by caseda** [comment]
i have tested if it functions with 2 reports in 1 capability.
(actually already dit test it before, but completely forgot 😅)
Not on this module though, but on another module, same principle

i think you do need to be sure not both reports can get triggered.
that will cause 2 flow triggers.

But in this case it really only triggers 1 report at a time
GET -> REPORT on Binary Sensor CC (status when app starts-up)
BASIC_SET (report) on Basic CC (hardware changes)

tested this with the FGBS-001 which i am using with 2 different CC's, but also 2 reports in 1.
GET -> REPORT on Binary Switch CC (status when app starts-up)
SCENE_ACTIVATION_SET (report) on Scene Activation CC (hardware changes)

**Comment by RobinBol** [comment]
In what case does your device send basic_set when it is triggered? I have tested and only binary reports come in, and the device works as expected?

**Comment by caseda** [comment]
are you sure you are testing with the FGK-101 (non z-wave plus version

have seen one real life case, and debugged with that case to fix this issue (also why the code was down below before this addition to just combine it into the capability)
you can ask "blusser"on the forum (don't know what name he goes by on github) for that case a while back (start of september this year)

small sample of the debug log back then:
```
[debug] node.on('online') arguments: { '0': true }
[debug] node.CommandClass['COMMAND_CLASS_BASIC'].on('report') arguments: { '0': { value: 1, name: 'BASIC_SET' },
  '1': { 'Value (Raw)': <Buffer 00>, Value: 0 },
  '2': null }
[DEBUG] Basic Report:
{ 'Value (Raw)': <Buffer 00>, Value: 0 }
[debug] node.on('online') arguments: { '0': false }
[debug] node.on('online') arguments: { '0': true }
[debug] node.CommandClass['COMMAND_CLASS_BASIC'].on('report') arguments: { '0': { value: 1, name: 'BASIC_SET' },
  '1': { 'Value (Raw)': <Buffer ff>, Value: 255 },
  '2': null }
[DEBUG] Basic Report:
{ 'Value (Raw)': <Buffer ff>, Value: 255 }
[debug]  COMMAND_CLASS_BATTERY BATTERY_GET args: {} err: { [Error: TRANSMIT_COMPLETE_NO_ACK] message: 'TRANSMIT_COMPLETE_NO_ACK' } result: null
[debug] node.on('online') arguments: { '0': false }
[debug] node.on('online') arguments: { '0': true }
[debug] node.CommandClass['COMMAND_CLASS_BASIC'].on('report') arguments: { '0': { value: 1, name: 'BASIC_SET' },
  '1': { 'Value (Raw)': <Buffer 00>, Value: 0 },
  '2': null }
[DEBUG] Basic Report:
{ 'Value (Raw)': <Buffer 00>, Value: 0 }
[debug] node.on('online') arguments: { '0': false }
[debug] node.on('online') arguments: { '0': true }
[debug] node.CommandClass['COMMAND_CLASS_BASIC'].on('report') arguments: { '0': { value: 1, name: 'BASIC_SET' },
  '1': { 'Value (Raw)': <Buffer ff>, Value: 255 },
  '2': null }
[DEBUG] Basic Report:
{ 'Value (Raw)': <Buffer ff>, Value: 255 }
[debug] node.on('online') arguments: { '0': false }
```

there are a few z-wave devices that only send the basic_set command on hardware changes, not just this sensor, even though it is the only one of fibaro

or it must have been fixed in the last 2,5 months that there were many updates, but not very likely since homey is not the only controller with the same issue

**Comment by RobinBol** [comment]
Hm very strange, yes I am using FGK-101, but it has 3 productIds so maybe that is were the discrepancy is coming from. Will include basic set as well. Thanks!

**Pull request closed without merging**
