### PR TITLE
FGDW-002 (Door/Window Sensor) support

### PR DESCRIPTION
**Pull request by RobinBol**
@caseda can not assign you as reviewer, but if you'd like please take a look!

### CODE REVIEW

**Comment by jeroenvollenbrock** [comment]
Please note that this device requires 1.3.0-rc.11 or above due to a bugfix

**Comment by TedTolboom** [comment]
@RobinBol check you signed: false flags... 
Missing them on parameters 14, 15, 30, 50, 52

Didn't check the rest of the code...

**Comment by RobinBol** [comment]
Well, correct me if I am wrong, but all those parameters have a value range from 0 - 32400, and byte size 2. I often use [this reference](https://msdn.microsoft.com/en-us/library/aa263420(v=vs.60).aspx) to check the default value ranges. As you can see 2 bytes give a value range from -32768 to 32767 which 0 - 32400 fits perfectly in.

**Comment by TedTolboom** [comment]
@RobinBol you're right... shouldn't try to multitask... ;-P

**Comment by RobinBol** [comment]
No problem, thanks for checking:)

**Comment by caseda** [comment]
Hope you will update compatibility too then, if people decide not to update immediately, or just don't want want to auto update, or worse don't update at all for some reason. 😅

further the code looks good.
Only able to test later this evening though.

**Comment by RobinBol** [comment]
Good point, just updated compatibility. But will not merge this PR before 1.3.0 hits stable.

Thanks for checking, but you probably won't be able to to pair the device (see Jeroen's comment).

**Comment by caseda** [comment]
Yes I am, rc11 is in experimental

**Comment by caseda** [comment]
even though it's not documented in the manual, it is possible to turn of the LED completely with value 0, are you willing to add that? 😄 

Further it works pretty good!

**Pull request merged**
