### PR TITLE
fgms-001 temperature offset is signed

### PR DESCRIPTION
**Pull request by caseda**
according to an comment on the appstore noticed the signed was set false, even though it is a signed buffer (-1000 - +1000)

### CODE REVIEW

**Comment by RobinBol** [comment]
I don't think that is the issue.

According to the docs:
```
66. TEMPERATURE OFFSET
The value to be added to the actual temperature, measured by the
sensor (temperature compensation).
 Available settings: 0 - 100 (0 to 100oC) or 64536 - 65535 (-100 to
-0.10oC)
Default setting: 0
Parameter size: 2 [bytes]
```

So 2 bytes have a range of 0 to 65,535. But the `temperature_offset` uses this as range:
```
"attr": {
		"min": -1000,
		"max": 1000
	},
```

**Comment by caseda** [comment]
Yeah so it should still be signed, since it work in negatives, Unsigned is as you say just from 0, the offset works in -100.0 - +100.0
With Unsigned you can't get negative unless you parse it yourself to signed values

**Comment by RobinBol** [comment]
It does not work in negatives, if I make the setting signed it will have a range of –32,768 to 32,767 which is too small.

So the range in app.json should be 0 - 65535, problem is that only 0 - 100 and 64536 - 65535 are valid values.

**Comment by caseda** [comment]
Too small? 1000 is way within the 32000 range for me
Signed is in decimal =  -32767 - +32767

Though hexadecimal doesn't have negatives, with negative you count backwards from the max so FFFF = -1 in decimal
FFFE = - 2 etc

This is what signed does, and is meant for

**Comment by RobinBol** [comment]
Yes, or I am really misunderstanding you, or you did not read the documentation on the setting properly, the range for the setting is 0 - 100 (for positive offset) or 64536 - 65535 (for negative offset), so in total a range of 0 - 65535.

**Comment by caseda** [comment]
I'll explain it in this way, forget what is in the manual for a second. 

_Signed range:_
Decimal (used in the driver):
-32767
+32767
Hexadecimal (used in zwave):
0000 (+0)
8FFE (+32767)
8FFF (-32767)
FFFF (-1)

_Unsigned range:_
Decimal (used in driver):
+0
+65535
Hexadecimal (used in zwave):
0000 (+0)
FFFF (+65535)

So if you want a range that is negative _Unsigned_, you need a range of 65535 to 0 but block everything in between.
And convert _yourself_ that the value is subtracted from the max.
-1 = 65535;
-10 = 65525;
Etc
OR explain the user that 65535 == -1 so they will have to convert it them selves... Not really user friendly 

But if you parse it _signed_ it _automatically_ does that conversion for negative,
so -1 === 65535
-10 === 65525
No need for any big range and block everything inbetween and convertion parser.

So a range in the driver when parsed signed:
-1000 - +1000 ===
65535 - 64536 for negative
0 - 1000 for postive
No parser and explanation needed.

Range in driver when parsed unsigned,
Option 1 (explaining user)
65535 - 0
And make sure the user can't use values between 64535 and 1001
Option 2 (convert ourselves)
-1000 - +1000
And then convert ourselves in the poster that -1000 == 64536 etc. 

I rather have the signed way, where I can use negative values (like you can with the Offset or better called calibration) and _don't_ have to do any explanation to the user how they can convert, or convert it myself, which is more prone to errors. 

Though the Range is wrong, and should be just -100 to 100 (instead of 1000), but a full 2 byte range is not needed with a signed parsed value

**Comment by RobinBol** [comment]
Tested and fixed:
FGMS-001: https://github.com/athombv/com.fibaro/commit/482b00ba028ee77e84d28819d048e670c31971a4
FGM-001-PLUS: https://github.com/athombv/com.fibaro/commit/d6f70d2b1ecf6fc2058f6e2442bc995161a3706f

Agreed?:)

**Comment by caseda** [comment]
mmm, i would leave/add the 0.1 step :p
at least for the plus,
the normal it is indeed only 0.1 steps for the negative 😕 the positive is steps of 1.0 (weird thing to do)

**Comment by RobinBol** [comment]
Why? You can just set an offset of 2.5 for example, which will result in adding 2.5 degrees celsius to the measured temperature value.

**Comment by caseda** [comment]
ow, i thought that would disable the settings button without setting a step, my bad. 😄

**Comment by caseda** [comment]
i approve the changes (maybe the missing `;` of the normal fgms return :p though that won't break the driver)

and will close this PR

**Pull request closed without merging**
