### PR TITLE
Add new product id for flood sensor

### PR DESCRIPTION
**Pull request by mlund**
Fix for issues #238

### CODE REVIEW

**Comment by MatthewWaanders** [comment]
Hey there!

First off, thanks for your PR, community development is always appreciated.

Does this code still validate when you run `Athom app validate -l publish`? We've deprecated setting IDs being numbers in the past, and the SDK1 Fibaro app uses a lot of those.

I've taken your changes and copied them into the SDK2 rewrite of the Fibaro app!

**Comment by mlund** [comment]
Homey just shipped to the Canary Islands, and I thus cannot test before my own arrival. Is SDK2 in the `feature/sdk2` branch and is this in a reasonable working stage for testing?

**Comment by MatthewWaanders** [comment]
The SDK2 rewrite is indeed a WIP on the `feature/sdk2` branch, there's still 5 devices missing and I can't 100% guarantee the functioning of the devices since testing has been limited so far. I can tell you that the people that are voluntarily testing it gave a lot of positive feedback!

**Comment by dajojonl** [comment]
Please add :
Universal binary sensor
Product type ID: 1281
Product.         ID: 258

**Pull request closed without merging**
